services:
  - type: web
    name: metrolima-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh || pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn metrolima_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: metrolima_api.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PORT
        sync: false

