services:
  - type: web
    name: metrolima-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn metrolima_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: metrolima_api.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PORT
        sync: false

