services:
  - type: web
    name: metrolima-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: metrolima_api.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PORT
        sync: false

